config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :about_projects, :project_news, :coaches, :blogs, :blog_article, :defaults => {:format => 'json'}
    end
  end

  namespace :ui do
    get 'pelican/index'
  end

end

app/models/about_project.rb
class AboutProject < ActiveRecord::Base
end

app/controllers/api/v1/about_projects_controller.rb
module Api
  module V1

    class AboutProjectsController < ApplicationController
      before_action :set_about_project, only: [:show, :edit, :update, :destroy]

      # GET /about_projects
      # GET /about_projects.json
      def index
        @about_projects = AboutProject.last(1)

        respond_to do |format|
          format.json {render json: @about_projects[0], :only => [:description]}
        end
      end

      # GET /about_projects/1
      # GET /about_projects/1.json
      def show
      end

      # GET /about_projects/new
      def new
        @about_project = AboutProject.new
      end

      # GET /about_projects/1/edit
      def edit
      end

      # POST /about_projects
      # POST /about_projects.json
      def create
        @about_project = AboutProject.new(about_project_params)

        respond_to do |format|
          if @about_project.save
            format.html { redirect_to @about_project, notice: 'About project was successfully created.' }
            format.json { render :show, status: :created, location: @about_project }
          else
            format.html { render :new }
            format.json { render json: @about_project.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /about_projects/1
      # PATCH/PUT /about_projects/1.json
      def update
        respond_to do |format|
          if @about_project.update(about_project_params)
            format.html { redirect_to @about_project, notice: 'About project was successfully updated.' }
            format.json { render :show, status: :ok, location: @about_project }
          else
            format.html { render :edit }
            format.json { render json: @about_project.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /about_projects/1
      # DELETE /about_projects/1.json
      def destroy
        @about_project.destroy
        respond_to do |format|
          format.html { redirect_to about_projects_url, notice: 'About project was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_about_project
        @about_project = AboutProject.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def about_project_params
        params.require(:about_project).permit(:decription)
      end
    end
  end
end

app/helpers/about_projects_helper.rb
module AboutProjectsHelper
end

app/views/about_projects/_form.html.erb
<%= form_for(@about_project) do |f| %>
  <% if @about_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about_project.errors.count, "error") %> prohibited this about_project from being saved:</h2>

      <ul>
      <% @about_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :decription %><br>
    <%= f.text_field :decription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/about_projects/edit.html.erb
<h1>Editing about_project</h1>

<%= render 'form' %>

<%= link_to 'Show', @about_project %> |
<%= link_to 'Back', about_projects_path %>

app/views/about_projects/index.html.erb
<h1>Listing about_projects</h1>

<table>
  <thead>
    <tr>
      <th>Decription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @about_projects.each do |about_project| %>
      <tr>
        <td><%= about_project.decription %></td>
        <td><%= link_to 'Show', about_project %></td>
        <td><%= link_to 'Edit', edit_about_project_path(about_project) %></td>
        <td><%= link_to 'Destroy', about_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New About project', new_about_project_path %>

app/views/about_projects/new.html.erb
<h1>New about_project</h1>

<%= render 'form' %>

<%= link_to 'Back', about_projects_path %>

app/views/about_projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Decription:</strong>
  <%= @about_project.decription %>
</p>

<%= link_to 'Edit', edit_about_project_path(@about_project) %> |
<%= link_to 'Back', about_projects_path %>