config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :about_projects, :project_news, :coaches, :blogs, :blog_article, :defaults => {:format => 'json'}
    end
  end

  namespace :ui do
    get 'pelican/index'
  end

end

app/models/project_news.rb
class ProjectNews < ActiveRecord::Base
end

app/controllers/api/v1/project_news_controller.rb
module Api
  module V1
    class ProjectNewsController < ApplicationController
      before_action :set_project_news, only: [:show, :edit, :update, :destroy]

      # GET /project_news
      # GET /project_news.json
      def index
        @project_news = ProjectNews.last(10)
        respond_to do |format|
          format.json {render json: @project_news, :only => [:date, :content, :tags]}
        end
      end

      # GET /project_news/1
      # GET /project_news/1.json
      def show
      end

      # GET /project_news/new
      def new
        @project_news = ProjectNews.new
      end

      # GET /project_news/1/edit
      def edit
      end

      # POST /project_news
      # POST /project_news.json
      def create
        @project_news = ProjectNews.new(project_news_params)

        respond_to do |format|
          if @project_news.save
            format.html { redirect_to @project_news, notice: 'Project news was successfully created.' }
            format.json { render :show, status: :created, location: @project_news }
          else
            format.html { render :new }
            format.json { render json: @project_news.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /project_news/1
      # PATCH/PUT /project_news/1.json
      def update
        respond_to do |format|
          if @project_news.update(project_news_params)
            format.html { redirect_to @project_news, notice: 'Project news was successfully updated.' }
            format.json { render :show, status: :ok, location: @project_news }
          else
            format.html { render :edit }
            format.json { render json: @project_news.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /project_news/1
      # DELETE /project_news/1.json
      def destroy
        @project_news.destroy
        respond_to do |format|
          format.html { redirect_to project_news_index_url, notice: 'Project news was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_project_news
        @project_news = ProjectNews.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def project_news_params
        params.require(:project_news).permit(:date, :content, :tags)
      end
    end
  end
end

app/helpers/project_news_helper.rb
module ProjectNewsHelper
end

app/views/project_news/_form.html.erb
<%= form_for(@project_news) do |f| %>
  <% if @project_news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_news.errors.count, "error") %> prohibited this project_news from being saved:</h2>

      <ul>
      <% @project_news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_news/edit.html.erb
<h1>Editing project_news</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_news %> |
<%= link_to 'Back', project_news_index_path %>

app/views/project_news/index.html.erb
<h1>Listing project_news</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Content</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_news.each do |project_news| %>
      <tr>
        <td><%= project_news.date %></td>
        <td><%= project_news.content %></td>
        <td><%= project_news.tags %></td>
        <td><%= link_to 'Show', project_news %></td>
        <td><%= link_to 'Edit', edit_project_news_path(project_news) %></td>
        <td><%= link_to 'Destroy', project_news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project news', new_project_news_path %>

app/views/project_news/new.html.erb
<h1>New project_news</h1>

<%= render 'form' %>

<%= link_to 'Back', project_news_index_path %>

app/views/project_news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @project_news.date %>
</p>

<p>
  <strong>Content:</strong>
  <%= @project_news.content %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @project_news.tags %>
</p>

<%= link_to 'Edit', edit_project_news_path(@project_news) %> |
<%= link_to 'Back', project_news_index_path %>