config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :about_projects, :project_news, :coaches, :blogs, :blog_article, :defaults => {:format => 'json'}
    end
  end

  namespace :ui do
    get 'pelican/index'
  end

end

app/models/coach.rb
class Coach < ActiveRecord::Base
end

app/controllers/api/v1/coaches_controller.rb
module Api
  module V1
    class CoachesController < ApplicationController
      before_action :set_coach, only: [:show, :edit, :update, :destroy]

      # GET /coaches
      # GET /coaches.json
      def index
        @coaches = Coach.all
        respond_to do |format|
          format.json {render json: @coaches, :only => [:name, :photo, :description]}
        end
      end

      # GET /coaches/1
      # GET /coaches/1.json
      def show
      end

      # GET /coaches/new
      def new
        @coach = Coach.new
      end

      # GET /coaches/1/edit
      def edit
      end

      # POST /coaches
      # POST /coaches.json
      def create
        @coach = Coach.new(coach_params)

        respond_to do |format|
          if @coach.save
            format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
            format.json { render :show, status: :created, location: @coach }
          else
            format.html { render :new }
            format.json { render json: @coach.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /coaches/1
      # PATCH/PUT /coaches/1.json
      def update
        respond_to do |format|
          if @coach.update(coach_params)
            format.html { redirect_to @coach, notice: 'Coach was successfully updated.' }
            format.json { render :show, status: :ok, location: @coach }
          else
            format.html { render :edit }
            format.json { render json: @coach.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /coaches/1
      # DELETE /coaches/1.json
      def destroy
        @coach.destroy
        respond_to do |format|
          format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_coach
        @coach = Coach.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def coach_params
        params.require(:coach).permit(:name, :photo, :description)
      end
    end
  end
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/_form.html.erb
<%= form_for(@coach) do |f| %>
  <% if @coach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

      <ul>
      <% @coach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coaches/edit.html.erb
<h1>Editing coach</h1>

<%= render 'form' %>

<%= link_to 'Show', @coach %> |
<%= link_to 'Back', coaches_path %>

app/views/coaches/index.html.erb
<h1>Listing coaches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Photo</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coaches.each do |coach| %>
      <tr>
        <td><%= coach.name %></td>
        <td><%= coach.photo %></td>
        <td><%= coach.description %></td>
        <td><%= link_to 'Show', coach %></td>
        <td><%= link_to 'Edit', edit_coach_path(coach) %></td>
        <td><%= link_to 'Destroy', coach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coach', new_coach_path %>

app/views/coaches/new.html.erb
<h1>New coach</h1>

<%= render 'form' %>

<%= link_to 'Back', coaches_path %>

app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coach.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @coach.photo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @coach.description %>
</p>

<%= link_to 'Edit', edit_coach_path(@coach) %> |
<%= link_to 'Back', coaches_path %>